<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE registry [
<!ELEMENT registry (entry*,folder*)>
<!ELEMENT folder (entry*,folder*)>
<!ELEMENT entry EMPTY>
<!ATTLIST folder key CDATA #REQUIRED>
<!ATTLIST entry key CDATA #REQUIRED>
<!ATTLIST entry value CDATA #REQUIRED>
]>
<registry>
  <entry key="NumberOfControlPoints" value="10" />
  <entry key="Preset" value="Custom" />
  <folder key="ControlPoint[0000]" >
    <entry key="Index" value="0" />
    <entry key="Type" value="Discontinuous" />
    <folder key="Left" >
      <entry key="A" value="0" />
      <entry key="B" value="0" />
      <entry key="G" value="0" />
      <entry key="R" value="0" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="0" />
      <entry key="G" value="0" />
      <entry key="R" value="0" />
    </folder>
  </folder>
  <folder key="ControlPoint[0001]" >
    <entry key="Index" value="0" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="84" />
      <entry key="G" value="1" />
      <entry key="R" value="68" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="84" />
      <entry key="G" value="1" />
      <entry key="R" value="68" />
    </folder>
  </folder>
  <folder key="ControlPoint[0002]" >
    <entry key="Index" value="0.125" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="123" />
      <entry key="G" value="45" />
      <entry key="R" value="71" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="123" />
      <entry key="G" value="45" />
      <entry key="R" value="71" />
    </folder>
  </folder>
  <folder key="ControlPoint[0003]" >
    <entry key="Index" value="0.25" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="139" />
      <entry key="G" value="82" />
      <entry key="R" value="59" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="139" />
      <entry key="G" value="82" />
      <entry key="R" value="59" />
    </folder>
  </folder>
  <folder key="ControlPoint[0004]" >
    <entry key="Index" value="0.375" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="142" />
      <entry key="G" value="114" />
      <entry key="R" value="44" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="142" />
      <entry key="G" value="114" />
      <entry key="R" value="44" />
    </folder>
  </folder>
  <folder key="ControlPoint[0005]" >
    <entry key="Index" value="0.5" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="140" />
      <entry key="G" value="145" />
      <entry key="R" value="33" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="140" />
      <entry key="G" value="145" />
      <entry key="R" value="33" />
    </folder>
  </folder>
  <folder key="ControlPoint[0006]" >
    <entry key="Index" value="0.625" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="128" />
      <entry key="G" value="174" />
      <entry key="R" value="40" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="128" />
      <entry key="G" value="174" />
      <entry key="R" value="40" />
    </folder>
  </folder>
  <folder key="ControlPoint[0007]" >
    <entry key="Index" value="0.75" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="98" />
      <entry key="G" value="201" />
      <entry key="R" value="94" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="98" />
      <entry key="G" value="201" />
      <entry key="R" value="94" />
    </folder>
  </folder>
  <folder key="ControlPoint[0008]" >
    <entry key="Index" value="0.875" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="48" />
      <entry key="G" value="220" />
      <entry key="R" value="173" />>
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="48" />
      <entry key="G" value="220" />
      <entry key="R" value="173" />
    </folder>
  </folder>
  <folder key="ControlPoint[0009]" >
    <entry key="Index" value="1" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="37" />
      <entry key="G" value="231" />
      <entry key="R" value="253" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="37" />
      <entry key="G" value="231" />
      <entry key="R" value="253" />
    </folder>
  </folder>
  <folder key="NaNColor" >
    <entry key="A" value="255" />
    <entry key="B" value="0" />
    <entry key="G" value="0" />
    <entry key="R" value="0" />
  </folder>
</registry>
