<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE registry [
<!ELEMENT registry (entry*,folder*)>
<!ELEMENT folder (entry*,folder*)>
<!ELEMENT entry EMPTY>
<!ATTLIST folder key CDATA #REQUIRED>
<!ATTLIST entry key CDATA #REQUIRED>
<!ATTLIST entry value CDATA #REQUIRED>
]>
<registry>
  <entry key="NumberOfControlPoints" value="10" />
  <entry key="Preset" value="Custom" />
  <folder key="ControlPoint[0000]" >
    <entry key="Index" value="0" />
    <entry key="Type" value="Discontinuous" />
    <folder key="Left" >
      <entry key="A" value="0" />
      <entry key="B" value="0" />
      <entry key="G" value="0" />
      <entry key="R" value="0" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="0" />
      <entry key="G" value="0" />
      <entry key="R" value="0" />
    </folder>
  </folder>
  <folder key="ControlPoint[0001]" >
    <entry key="Index" value="0" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="76" />
      <entry key="G" value="26" />
      <entry key="R" value="44" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="76" />
      <entry key="G" value="26" />
      <entry key="R" value="44" />
    </folder>
  </folder>
  <folder key="ControlPoint[0002]" >
    <entry key="Index" value="0.125" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="106" />
      <entry key="G" value="56" />
      <entry key="R" value="41" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="106" />
      <entry key="G" value="56" />
      <entry key="R" value="41" />
    </folder>
  </folder>
  <folder key="ControlPoint[0003]" >
    <entry key="Index" value="0.25" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="143" />
      <entry key="G" value="88" />
      <entry key="R" value="41" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="143" />
      <entry key="G" value="88" />
      <entry key="R" value="41" />
    </folder>
  </folder>
  <folder key="ControlPoint[0004]" >
    <entry key="Index" value="0.375" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="188" />
      <entry key="G" value="114" />
      <entry key="R" value="66" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="188" />
      <entry key="G" value="114" />
      <entry key="R" value="66" />
    </folder>
  </folder>
  <folder key="ControlPoint[0005]" >
    <entry key="Index" value="0.5" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="221" />
      <entry key="G" value="143" />
      <entry key="R" value="126" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="221" />
      <entry key="G" value="143" />
      <entry key="R" value="126" />
    </folder>
  </folder>
  <folder key="ControlPoint[0006]" >
    <entry key="Index" value="0.625" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="238" />
      <entry key="G" value="171" />
      <entry key="R" value="176" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="238" />
      <entry key="G" value="171" />
      <entry key="R" value="176" />
    </folder>
  </folder>
  <folder key="ControlPoint[0007]" >
    <entry key="Index" value="0.75" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="244" />
      <entry key="G" value="198" />
      <entry key="R" value="203" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="244" />
      <entry key="G" value="198" />
      <entry key="R" value="203" />
    </folder>
  </folder>
  <folder key="ControlPoint[0008]" >
    <entry key="Index" value="0.875" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="250" />
      <entry key="G" value="227" />
      <entry key="R" value="229" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="250" />
      <entry key="G" value="227" />
      <entry key="R" value="229" />
    </folder>
  </folder>
  <folder key="ControlPoint[0009]" >
    <entry key="Index" value="1" />
    <entry key="Type" value="Continuous" />
    <folder key="Left" >
      <entry key="A" value="255" />
      <entry key="B" value="255" />
      <entry key="G" value="255" />
      <entry key="R" value="255" />
    </folder>
    <folder key="Right" >
      <entry key="A" value="255" />
      <entry key="B" value="255" />
      <entry key="G" value="255" />
      <entry key="R" value="255" />
    </folder>
  </folder>
  <folder key="NaNColor" >
    <entry key="A" value="255" />
    <entry key="B" value="0" />
    <entry key="G" value="0" />
    <entry key="R" value="0" />
  </folder>
</registry>
